version: '3'
services:
  tcp_server:
    build:
      context: .
      dockerfile: tcp_server
    ports:
      - 5000:5000
    command: python /app/tcp_server.py
    image: tcp_server
  receive_message:
    build:
      context: .
      dockerfile: receive_message
    command: python /app/receive_message.py
    image: receive_message
    depends_on:
      - tcp_server
